FLAG = -Wall -Werror  -g

tinybc: tinybc.c
	gcc -o tinybc tinybc.c $(FLAG)
 
popendemo: popendemo.c
	gcc -o popendemo popendemo.c $(FLAG)

timeserv: timeserv.c
	gcc -o timesev timeserv.c $(FLAG)

timeclnt: timeclnt.c
	gcc -o timeclnt timeclnt.c $(FLAG)
