FLAG = -Wall -Werror

psh1: psh1.c
	gcc -o psh1 psh1.c $(FLAG)

fork: forkdemo1.c
	gcc -o forkdemo1 forkdemo1.c $(FLAG)

fork2: forkdemo2.c
	gcc -o forkdemo2 forkdemo2.c $(FLAG)

wait: waitdemo1.c
	gcc -o wait waitdemo1.c $(FLAG)

wait2: waitdemo2.c
	gcc -o wait2 waitdemo2.c $(FLAG)
