FLAG = -Wall -Werror

1: listargs.c
	gcc listargs.c $(FLAG)

2: stdinredir1.c
	gcc stdinredir1.c $(FLAG)

3: stdinredir2.c 
	gcc stdinredir2.c $(FLAG)

4: whotofile.c
	gcc whotofile.c -Wall

pipe1: pipedemo.c
	gcc pipedemo.c $(FLAG)

pipe2: pipedemo2.c
	gcc pipedemo2.c $(FLAG)

pipe: pipe.c
	gcc pipe.c $(FLAG)
