FLAG = -Wall -Werror

rotate: rotate.c
	gcc -o rotate rotate.c $(FLAG)

0: play_again0.c
	gcc -o play_again0 play_again0.c $(FLAG)

1: play_again1.c
	gcc -o play_again1 play_again1.c $(FLAG)

2: play_again2.c
	gcc -o play_again2 play_again2.c $(FLAG)

sig1: sigdemo1.c
	gcc -o sigdemo1 sigdemo1.c $(FLAG)

sig2: sigdemo2.c
	gcc -o sigdemo2 sigdemo2.c $(FLAG)
