FLAG = -Wall -Werror

write0: write0.c
	gcc -o write0 write0.c $(FLAG)

listchars: listchars.c
	gcc -o listchars listchars.c $(FLAG)

echostate: echostate.c
	gcc -o echostate echostate.c $(FLAG)

setecho: setecho.c
	gcc -o setecho setecho.c $(FLAG)

showtty: showtty.c
	gcc -o showtty showtty.c $(FLAG)
